site_name: Miku
site_url: 'http://localhost:8000'

repo_name: blanketsucks/miku
repo_url: https://github.com/blanketsucks/miku

theme:
  name: "material"
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode


nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - API Reference:
    - AsyncAnilistClient: API-Reference/client.md
    - Media: API-Reference/media.md
    - MediaStatus: API-Reference/media-status.md
    - MediaFormat: API-Reference/media-format.md
    - MediaType: API-Reference/media-type.md
    - MediaSource: API-Reference/media-source.md
    - MediaTitle: API-Reference/media-title.md
    - Character: API-Reference/character.md
    - CharacterName: API-Reference/character-name.md
    - CharacterBirthdate: API-Reference/character-birthdate.md
    - User: API-Reference/user.md
    - UserFavourites: API-Reference/user-favourites.md
    - UserOptions: API-Reference/user-options.md
    - UserTitleLanguage: API-Reference/user-title-language.md
    - UserNotificationOption: API-Reference/user-notification.md
    - UserNotificationOptionType: API-Reference/user-notification-type.md
    - Staff: API-Reference/staff.md
    - Studio: API-Reference/studio.md
    - SiteStatistics: API-Reference/site-statistics.md
    - SiteTrend: API-Reference/site-trend.md
    - Image: API-Reference/image.md
    - Paginator: API-Reference/paginator.md
    - Page: API-Reference/page.md
    - Data: API-Reference/data.md

plugins:
- search
- mkdocstrings

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition