site_name: Miku

repo_name: blanketsucks/miku
repo_url: https://github.com/blanketsucks/miku

theme:
  name: "material"

nav:
  - Home: index.md
  - Basic-Example: basic-example.md
  - API-Reference:
    - Client: API-Reference/client.md
    - Media: API-Reference/media.md
    - Character: API-Reference/media.md
    - Image: API-Reference/image.md
    - Paginator: API-Reference/paginator.md
    - Page: API-Reference/page.md

plugins:
- search
- mkdocstrings

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition